### ISSUE TITLE
anim_picker: make select controls display more noticeable 

### ISSUE THREAD

**Issue by jdrese** [mgear-dev/anim_picker#16]
We can revert this if you like the old version better but I've receive remarks from animators saying that the default select controls feedback is too discreet

**Comment by jdrese** [comment]
I've pushed this.
https://github.com/mgear-dev/anim_picker/commit/242fda10155401202b9b719e004b73d259226570

**Comment by miquelcampos** [comment]
@jdrese  this ticket can be closed?

**Comment by jdrese** [comment]
Yes it can. Sorry I didn't close it with the commit. Was waiting for your feedback on it. Closing it now

**Comment by miquelcampos** [comment]
@jdrese  thanks!!
