### ISSUE TITLE
Zooming with modifier and mouse button, Pen/tablet support

### ISSUE THREAD

**Issue by RafaelVillar** [mgear-dev/anim_picker#37]
More details here
[http://forum.mgear-framework.com/t/animpicker-how-to-use/1769/2?u=rafael](url)

Since the only way to zoom on the anim picker is with scroll, this can leave out pen/tablet users. So this is an initial attempt to help with that issue. 

Currently mimicking Maya's Alt+ Right click to zoom.
![animpicker_v001](https://user-images.githubusercontent.com/7085330/97777871-56408980-1bb6-11eb-9223-98d2d41d1f80.gif)

In the anim picker ui, like so
![animpicker_v002](https://user-images.githubusercontent.com/7085330/97777879-67899600-1bb6-11eb-8c96-9fd428a8d7ce.gif)

Due to hot keys being so subjective, I just copied maya.

**Comment by miquelcampos** [comment]
This is great! Thanks @RafaelVillar !

**Comment by OliveMoustache** [comment]
Awesome!
