### ISSUE TITLE
Auto fit disable option on resize event

### ISSUE THREAD

**Issue by RafaelVillar** [mgear-dev/anim_picker#38]
Adding the option to disable auto fit contents on resize event(s)

As described here
http://forum.mgear-framework.com/t/animpicker-how-to-use/1769/6?

This is an initial implementation of being able to disable auto resize

**Comment by RafaelVillar** [comment]
![animpicker_v004](https://user-images.githubusercontent.com/7085330/97955340-5379aa80-1de9-11eb-8214-6ad26c2f521f.gif)

Example of the initial implementation

**Comment by OliveMoustache** [comment]
Yes! That looks perfect Rafael!!

**Comment by jparks-semc** [comment]
gui.py line 1173: 'module' object has no attribute 'dpi_scale' #

**Comment by RafaelVillar** [comment]
May change to auto default off, but looks to be ideal for now.
